name: to_do_list_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'  # Actualizado para requerir la versión mínima compatible de Dart

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.7  # Dependencia para Firebase Firestore

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
